services:

  database:
    env_file:
      - .env
    container_name: database
    image: mysql:9.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - ./db:/var/lib/mysql:delegated

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - database

  mailer:
    image: mailhog/mailhog
    container_name: mailer
    ports:
      - "8024:8025"
      - "1025:1025"
